stages:
  - convert
  - deploy

convert:
  image: python
  stage: convert
  rules:
    - if: $CI_COMMIT_BRANCH == "build-ci"
    - if: $CI_COMMIT_BRANCH == "master"
  before_script:
    - pip install casq
  script:
    - python .ci/convertCASQ.py

commit:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "build-ci"
    - if: $CI_COMMIT_BRANCH == "master"
  before_script:
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - git checkout -b $CI_COMMIT_REF_NAME
    - git remote set-url origin "https://$GIT_ACCESS_USER:$GIT_ACCESS_PASSWORD@${url_host}"
    - git config user.name $GIT_ACCESS_USER
    - git config user.email $GIT_ACCESS_EMAIL

  script:
    - git commit -am "Update models"
    - git push origin $CI_COMMIT_REF_NAME