stages:
  - convert
  - deploy

convert:
  image: python
  stage: convert
  rules:
    - if: $CI_MERGE_REQUEST_ID
  before_script:
    - pip install casq
  script:
    - python .ci/convertCASQ.py
  artifacts:
    expire_in: 1 day
    paths:
      - "Executable Modules"

commit:
  image:
    name: alpine/git:latest
    entrypoint: [""]
  stage: deploy
  rules:
    - if: $CI_MERGE_REQUEST_ID
  before_script:
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - git branch -d $CI_COMMIT_BRANCH # delete existing branch locally
    - git checkout -b $CI_COMMIT_BRANCH origin/$CI_COMMIT_BRANCH
    - git remote set-url origin "https://$GIT_ACCESS_USER:$GIT_ACCESS_TOKEN@${url_host}"
    - git config user.name $GIT_ACCESS_USER
    - git config user.email $GIT_ACCESS_EMAIL
  script:
    - git add --all
    - git commit -m "Update models"
    - git push origin $CI_COMMIT_BRANCH