stages:
  - convert
  - deploy

convert:
  image: python
  stage: convert
  rules:
    - if: $CI_COMMIT_BRANCH == "build-ci"
    - if: $CI_COMMIT_BRANCH == "master"
  before_script:
    - pip install casq
  script:
    - python .ci/convertCASQ.py

commit:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "build-ci"
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - echo " > This is the commit stage"